server:
  port: 8001
spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      database: 1
  mvc:
    view:
      prefix: /templates/
      suffix: .html
short-link:
  stats:
    locale:
      amap-key: 14182c72b602937a5cf02a374bf8d5cd
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml